package com.alarmcontrol.ml

/**
 * On-device classifier configuration. The vocabulary and labels are **not** hardcoded here: they
 * ship as bundled assets generated by `ml/training/train.py` alongside the `.tflite`, so the model,
 * its feature order, and its label order can never drift from one another (§5). Nothing is fetched —
 * all assets are local (§1/§3).
 *
 * When no model/vocab/labels are present (e.g. before the pipeline has been run), the classifier
 * degrades to rule-only filtering (§5).
 */
internal object MlConfig {
    const val MODEL_ASSET = "notification_classifier.tflite"
    const val VOCAB_ASSET = "vocab.txt"
    const val LABELS_ASSET = "labels.txt"

    /** Minimum top score for a categorization to be trusted; mirrored by the trainer's verification. */
    const val CONFIDENCE_THRESHOLD = 0.6f

    /**
     * Path (relative to the app's private `filesDir`) where the on-device generative LLM model is
     * expected (Milestone 4). The model is **not** bundled in the APK — it's far too large — so it's
     * imported by the user through local Storage Access Framework UI; if absent, the LLM analyzer
     * reports unavailable and the app falls back to rules + the classifier (§5). Nothing is ever
     * downloaded by the app (§3).
     */
    const val LLM_MODEL_FILE = "llm/ad-context-model.task"

    /** Upper bound on tokens the LLM may emit per analysis; keeps latency/memory bounded on-device. */
    const val LLM_MAX_TOKENS = 128
}
