package com.alarmcontrol.ml

/**
 * On-device classifier configuration. The vocabulary and labels are **not** hardcoded here: they
 * ship as bundled assets generated by `ml/training/train.py` alongside the `.tflite`, so the model,
 * its feature order, and its label order can never drift from one another (§5). Nothing is fetched —
 * all assets are local (§1/§3).
 *
 * When no model/vocab/labels are present (e.g. before the pipeline has been run), the classifier
 * degrades to rule-only filtering (§5).
 */
internal object MlConfig {
    const val MODEL_ASSET = "notification_classifier.tflite"
    const val VOCAB_ASSET = "vocab.txt"
    const val LABELS_ASSET = "labels.txt"

    /** Minimum top score for a categorization to be trusted; mirrored by the trainer's verification. */
    const val CONFIDENCE_THRESHOLD = 0.6f

    const val SEMANTIC_MODEL_ASSET = "semantic_notification_classifier.tflite"
    const val SEMANTIC_VOCAB_ASSET = "semantic_vocab.txt"
    const val SEMANTIC_LABELS_ASSET = "semantic_labels.txt"
    const val SEMANTIC_MODEL_MANIFEST_ASSET = "semantic_model_manifest.json"

    /**
     * Path (relative to the app's private `filesDir`) where the on-device generative LLM model is
     * expected (Milestone 4). The model is **not** bundled in the APK — it's far too large — so it's
     * imported by the user through local Storage Access Framework UI; if absent, the LLM analyzer
     * reports unavailable and the app falls back to rules + the classifier (§5). Nothing is ever
     * downloaded by the app (§3).
     */
    const val LLM_MODEL_FILE = "llm/ad-context-model.task"

    /**
     * Combined prompt + output context. This must match the KV-cache length used by
     * `ml/llm-training/convert_to_litert.py`; MediaPipe's `maxTokens` is not an output-only limit.
     */
    const val LLM_CONTEXT_TOKENS = 4_096

    /** Reserved inside [LLM_CONTEXT_TOKENS] for the compact JSON response and stop token. */
    const val LLM_OUTPUT_TOKEN_RESERVE = 128

    /** Greedy decoding keeps the classifier's strict JSON output deterministic. */
    const val LLM_TOP_K = 1
    const val LLM_TOP_P = 1.0f
    const val LLM_TEMPERATURE = 0.0f
    const val LLM_RANDOM_SEED = 20_260_727
}
