package com.alarmcontrol.automation

/**
 * The public, stable contract for controlling AlarmControl from external automation (CLAUDE.md §7).
 * Treat these strings like a public API — Tasker, MacroDroid, and compatible intent tools depend on
 * them, so do not rename or repurpose them casually. Samsung Modes & Routines should invoke the
 * first-party dynamic App Shortcuts instead; that path does not expose this token.
 *
 * Send an explicit broadcast targeted to package `com.alarmcontrol` (or
 * `ProfileToggleReceiver`) with one of the actions below and the required [EXTRA_AUTH_TOKEN] shown
 * in the app's Settings. Implicit broadcasts are rejected so other apps cannot observe the token.
 * Optionally include [EXTRA_PROFILE_ID] to target a
 * named profile by id or name. Legacy rule ids/names remain supported when no profile matches.
 * Omit it to change the independent filtering master switch. Pausing that switch preserves every
 * rule's individual enabled state.
 *
 * adb smoke test:
 * ```
 * adb shell am broadcast \
 *   -a com.alarmcontrol.automation.action.DISABLE_PROFILE \
 *   --es com.alarmcontrol.automation.extra.AUTH_TOKEN "<token-from-settings>" \
 *   -n com.alarmcontrol/com.alarmcontrol.automation.ProfileToggleReceiver
 * ```
 */
object AutomationContract {
    /** Enables the targeted rule, or the filtering master switch when no profile id is supplied. */
    const val ACTION_ENABLE_PROFILE = "com.alarmcontrol.automation.action.ENABLE_PROFILE"

    /** Disables the targeted rule, or the filtering master switch when no profile id is supplied. */
    const val ACTION_DISABLE_PROFILE = "com.alarmcontrol.automation.action.DISABLE_PROFILE"

    /**
     * Optional `String` extra naming a profile by id or case-insensitive name. When no profile
     * matches, legacy rule id/name resolution is used. When absent or blank, it targets the master.
     */
    const val EXTRA_PROFILE_ID = "com.alarmcontrol.automation.extra.PROFILE_ID"

    /** Required per-install `String` secret for exported broadcasts. Rotate it from Settings. */
    const val EXTRA_AUTH_TOKEN = "com.alarmcontrol.automation.extra.AUTH_TOKEN"
}

/**
 * Cheap ingress validation for the 32-byte, URL-safe Base64 token generated by `:data`. This is not
 * authentication; [ProfileController] still performs the constant-time comparison.
 */
internal fun String?.isPlausibleAutomationToken(): Boolean =
    this != null &&
        length == AUTOMATION_TOKEN_LENGTH &&
        all { character ->
            character in 'A'..'Z' ||
                character in 'a'..'z' ||
                character in '0'..'9' ||
                character == '-' ||
                character == '_'
        }

private const val AUTOMATION_TOKEN_LENGTH = 43
